<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260908052036 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE alimentation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type_nourriture VARCHAR(255) NOT NULL, quantite VARCHAR(100) NOT NULL, heure_repas TIME(0) WITHOUT TIME ZONE NOT NULL, animal_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8E65DFA08E962C16 ON alimentation (animal_id)');
        $this->addSql('CREATE TABLE avis (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom_visiteur VARCHAR(255) NOT NULL, contenu TEXT NOT NULL, note TEXT NOT NULL, date_avis TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, statut VARCHAR(50) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE compte_rendu (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, etat_animal VARCHAR(255) NOT NULL, nourriture VARCHAR(255) NOT NULL, grammage INT NOT NULL, date_passage TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, detail_etat TEXT DEFAULT NULL, animal_id INT NOT NULL, veterinaire_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D39E69D28E962C16 ON compte_rendu (animal_id)');
        $this->addSql('CREATE INDEX IDX_D39E69D25C80924 ON compte_rendu (veterinaire_id)');
        $this->addSql('ALTER TABLE alimentation ADD CONSTRAINT FK_8E65DFA08E962C16 FOREIGN KEY (animal_id) REFERENCES animal (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE compte_rendu ADD CONSTRAINT FK_D39E69D28E962C16 FOREIGN KEY (animal_id) REFERENCES animal (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE compte_rendu ADD CONSTRAINT FK_D39E69D25C80924 FOREIGN KEY (veterinaire_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE alimentation DROP CONSTRAINT FK_8E65DFA08E962C16');
        $this->addSql('ALTER TABLE compte_rendu DROP CONSTRAINT FK_D39E69D28E962C16');
        $this->addSql('ALTER TABLE compte_rendu DROP CONSTRAINT FK_D39E69D25C80924');
        $this->addSql('DROP TABLE alimentation');
        $this->addSql('DROP TABLE avis');
        $this->addSql('DROP TABLE compte_rendu');
    }
}
